{
    "driver": "com.mysql.jdbc.Driver",
    "url": "jdbc:mysql://10.209.6.9:3306/userinformation",
    "account": "ty",
    "password": "3856",
    "init_connections": 2,
    "core_connections": 6,
}